# Generated by Django 2.1.7 on 2019-04-21 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='article',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='chatuser',
            name='chatroom',
        ),
        migrations.RemoveField(
            model_name='chatuser',
            name='chatuser',
        ),
        migrations.RemoveField(
            model_name='friend',
            name='friend',
        ),
        migrations.RemoveField(
            model_name='friend',
            name='me',
        ),
        migrations.RemoveField(
            model_name='like',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='like',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='sasang',
            name='first',
        ),
        migrations.RemoveField(
            model_name='sasang',
            name='second',
        ),
        migrations.RemoveField(
            model_name='text',
            name='room',
        ),
        migrations.RemoveField(
            model_name='text',
            name='writer',
        ),
        migrations.DeleteModel(
            name='Article',
        ),
        migrations.DeleteModel(
            name='Chat',
        ),
        migrations.DeleteModel(
            name='ChatUser',
        ),
        migrations.DeleteModel(
            name='Friend',
        ),
        migrations.DeleteModel(
            name='Like',
        ),
        migrations.DeleteModel(
            name='Sasang',
        ),
        migrations.DeleteModel(
            name='Text',
        ),
    ]
