# Generated by Django 2.2 on 2019-04-25 15:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('homepage', '0002_auto_20190421_1420'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_type', models.CharField(max_length=50)),
                ('group_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='profile',
            name='mybelong',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='myimage',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='myintro',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='myname',
        ),
        migrations.CreateModel(
            name='Design',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('likes', models.IntegerField(default=0)),
                ('detail_body', models.CharField(choices=[('BK', 'Black'), ('BG', 'Beige'), ('BL', 'Blue'), ('IV', 'Ivory'), ('PK', 'Pink'), ('RD', 'Red'), ('WT', 'White')], default='BK', max_length=2)),
                ('detail_sleeve', models.CharField(choices=[('BK', 'Black'), ('BG', 'Beige'), ('BL', 'Blue'), ('IV', 'Ivory'), ('PK', 'Pink'), ('RD', 'Red'), ('WT', 'White')], default='WT', max_length=2)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homepage.Group')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='groups',
            field=models.ManyToManyField(to='homepage.Group'),
        ),
    ]
