# Generated by Django 2.2 on 2019-04-29 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0003_auto_20190425_1501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='group_type',
            field=models.CharField(choices=[('MJ', 'Major'), ('CL', 'Club')], default='MJ', max_length=2),
        ),
    ]
