# This is a sample build configuration for Python.
# Check our guides at https://confluence.atlassian.com/x/x4UWN for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
# image: python:3.5.1

pipelines:
#  custom:
#    frontend:
#      - step:
#          script:
#            - cd progress
#            - apt-get update
#            - apt-get install libxss1 libgconf2-4 libappindicator1 libindicator7 < yes.txt
#            - wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
#            - apt-get install -f
#            - dpkg -i google-chrome*.deb
#            - apt-get install unzip < yes.txt
#            - wget -N http://chromedriver.storage.googleapis.com/2.26/chromedriver_linux64.zip
#            - unzip chromedriver_linux64.zip
#            - chmod +x chromedriver
#            - mv -f chromedriver /usr/local/share/chromedriver
#            - ln -s /usr/local/share/chromedriver /usr/local/bin/chromedriver
#            - ln -s /usr/local/share/chromedriver /usr/bin/chromedriver
#            - pip install -r requirements.txt
#            - python3 inittest.py http://wlxyzlw.iptime.org:8000/
#            - python3 signUpChecker.py http://wlxyzlw.iptime.org:3000/
  custom:
    frontend:
    - step:
        image: node:6.9.4
        script:
          - cd frontend
          - npm install
          - npm test -- --coverage
          - cd ..
    backend:
    - step:
        image: python:3.5.1
        script: # Modify the commands below to build your repository.
          - cd progress
#          - apt-get update && apt-get install tmux
          - pip install -r requirements.txt
#          - rm -f tmp.db ../northfacebook_backend/db.sqlite3
#          - rm -r ../northfacebook_backend/homepage/migrations
#          - python3 ../northfacebook_backend/manage.py makemigrations homepage
#          - python3 ../northfacebook_backend/manage.py migrate
#- tmux new-session -s new-session -n backend "python3 ../northfacebook_backend/manage.py runserver 0.0.0.0:8000" \; new-window -n frontend "cd ../northfacebook_frontend; npm start" \; new-window -n testWindow "echo 'Wait 5 seconds for running server...'; sleep 5; python3 backend_tests.py http://127.0.0.1:8000/; sleep 3; tmux kill-session -t new-session"
          
