# Generated by Django 2.2 on 2019-04-16 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='design',
            name='detail_body',
            field=models.CharField(choices=[('BK', 'Black'), ('BG', 'Beige'), ('BL', 'Blue'), ('IV', 'Ivory'), ('PK', 'Pink'), ('RD', 'Red'), ('WT', 'White')], default='BK', max_length=2),
        ),
        migrations.AlterField(
            model_name='design',
            name='detail_sleeve',
            field=models.CharField(choices=[('BK', 'Black'), ('BG', 'Beige'), ('BL', 'Blue'), ('IV', 'Ivory'), ('PK', 'Pink'), ('RD', 'Red'), ('WT', 'White')], default='WT', max_length=2),
        ),
    ]
