# Generated by Django 2.2 on 2019-04-16 19:19

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0002_auto_20190417_0017'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='GwajamUser',
        ),
    ]
