const back_sleeve = [
require('./back_sleeve/back_sleeve00b7ee.png'),
require('./back_sleeve/back_sleeve001c58.png'),
require('./back_sleeve/back_sleeve0075a9.png'),
require('./back_sleeve/back_sleeve80c269.png'),
require('./back_sleeve/back_sleeve097c25.png'),
require('./back_sleeve/back_sleeve580b0b.png'),
require('./back_sleeve/back_sleeve601986.png'),
require('./back_sleeve/back_sleeve626262.png'),
require('./back_sleeve/back_sleeve910000.png'),
require('./back_sleeve/back_sleeveaa89bd.png'),
require('./back_sleeve/back_sleevefcfcfc.png'),
require('./back_sleeve/back_sleevef29c9f.png'),
require('./back_sleeve/back_sleevef39800.png'),
require('./back_sleeve/back_sleevefff45c.png'),
require('./back_sleeve/back_sleeve232323.png'),
]

const back_banding = [
require('./back_banding/back_banding00b7ee.png'),
require('./back_banding/back_banding001c58.png'),
require('./back_banding/back_banding0075a9.png'),
require('./back_banding/back_banding80c269.png'),
require('./back_banding/back_banding097c25.png'),
require('./back_banding/back_banding580b0b.png'),
require('./back_banding/back_banding601986.png'),
require('./back_banding/back_banding626262.png'),
require('./back_banding/back_banding910000.png'),
require('./back_banding/back_bandingaa89bd.png'),
require('./back_banding/back_bandingcfcfcf.png'),
require('./back_banding/back_bandingf29c9f.png'),
require('./back_banding/back_bandingf39800.png'),
require('./back_banding/back_bandingfff45c.png'),
require('./back_banding/back_banding232323.png'),
]

const back_body = [
require('./back_body/back_body00b7ee.png'),
require('./back_body/back_body001c58.png'),
require('./back_body/back_body0075a9.png'),
require('./back_body/back_body80c269.png'),
require('./back_body/back_body097c25.png'),
require('./back_body/back_body580b0b.png'),
require('./back_body/back_body232323.png'),
require('./back_body/back_body601986.png'),
require('./back_body/back_body626262.png'),
require('./back_body/back_body910000.png'),
require('./back_body/back_bodyaa89bd.png'),
require('./back_body/back_bodycfcfcf.png'),
require('./back_body/back_bodyf29c9f.png'),
require('./back_body/back_bodyf39800.png'),
require('./back_body/back_bodyfff45c.png'),
]

const back_stripe = [
require('./back_stripe/back_stripe00b7ee.png'),
require('./back_stripe/back_stripe001c58.png'),
require('./back_stripe/back_stripe0075a9.png'),
require('./back_stripe/back_stripe80c269.png'),
require('./back_stripe/back_stripe097c25.png'),
require('./back_stripe/back_stripe580b0b.png'),
require('./back_stripe/back_stripe232323.png'),
require('./back_stripe/back_stripe601986.png'),
require('./back_stripe/back_stripe910000.png'),
require('./back_stripe/back_stripeaa89bd.png'),
require('./back_stripe/back_stripecfcfcf.png'),
require('./back_stripe/back_stripef29c9f.png'),
require('./back_stripe/back_stripef39800.png'),
require('./back_stripe/back_stripefff45c.png'),
require('./back_stripe/back_stripefcfcfc.png'),

]

const front_sleeve = [
require('./front_sleeve/front_sleeve00b7ee.png'),
require('./front_sleeve/front_sleeve001c58.png'),
require('./front_sleeve/front_sleeve0075a9.png'),
require('./front_sleeve/front_sleeve80c269.png'),
require('./front_sleeve/front_sleeve097c25.png'),
require('./front_sleeve/front_sleeve580b0b.png'),
require('./front_sleeve/front_sleeve626262.png'),
require('./front_sleeve/front_sleeve601986.png'),
require('./front_sleeve/front_sleeve910000.png'),
require('./front_sleeve/front_sleeveaa89bd.png'),
require('./front_sleeve/front_sleevefcfcfc.png'),
require('./front_sleeve/front_sleevef29c9f.png'),
require('./front_sleeve/front_sleevef39800.png'),
require('./front_sleeve/front_sleevefff45c.png'),
require('./front_sleeve/front_sleeve232323.png'),
]


const front_body = [
require('./front_body/front_body00b7ee.png'),
require('./front_body/front_body001c58.png'),
require('./front_body/front_body0075a9.png'),
require('./front_body/front_body80c269.png'),
require('./front_body/front_body097c25.png'),
require('./front_body/front_body580b0b.png'),
require('./front_body/front_body601986.png'),
require('./front_body/front_body626262.png'),
require('./front_body/front_body910000.png'),
require('./front_body/front_bodyaa89bd.png'),
require('./front_body/front_body232323.png'),
require('./front_body/front_bodycfcfcf.png'),
require('./front_body/front_bodyf29c9f.png'),
require('./front_body/front_bodyf39800.png'),
require('./front_body/front_bodyfff45c.png'),
]

const front_button = [
require('./front_button/front_button00b7ee.png'),
require('./front_button/front_button001c58.png'),
require('./front_button/front_button0075a9.png'),
require('./front_button/front_button80c269.png'),
require('./front_button/front_button097c25.png'),
require('./front_button/front_button580b0b.png'),
require('./front_button/front_button601986.png'),
require('./front_button/front_button910000.png'),
require('./front_button/front_buttonaa89bd.png'),
require('./front_button/front_button232323.png'),
require('./front_button/front_buttoncfcfcf.png'),
require('./front_button/front_buttonf29c9f.png'),
require('./front_button/front_buttonf39800.png'),
require('./front_button/front_buttonfff45c.png'),
require('./front_button/front_buttonfcfcfc.png'),
]

const front_stripe = [
require('./front_stripe/front_stripe00b7ee.png'),
require('./front_stripe/front_stripe001c58.png'),
require('./front_stripe/front_stripe0075a9.png'),
require('./front_stripe/front_stripe80c269.png'),
require('./front_stripe/front_stripe097c25.png'),
require('./front_stripe/front_stripe580b0b.png'),
require('./front_stripe/front_stripe232323.png'),
require('./front_stripe/front_stripe601986.png'),
require('./front_stripe/front_stripe910000.png'),
require('./front_stripe/front_stripeaa89bd.png'),
require('./front_stripe/front_stripecfcfcf.png'),
require('./front_stripe/front_stripef29c9f.png'),
require('./front_stripe/front_stripef39800.png'),
require('./front_stripe/front_stripefff45c.png'),
require('./front_stripe/front_stripefcfcfc.png'),
]

const front_banding = [
require('./front_banding/front_banding00b7ee.png'),
require('./front_banding/front_banding001c58.png'),
require('./front_banding/front_banding0075a9.png'),
require('./front_banding/front_banding80c269.png'),
require('./front_banding/front_banding097c25.png'),
require('./front_banding/front_banding580b0b.png'),
require('./front_banding/front_banding232323.png'),
require('./front_banding/front_banding601986.png'),
require('./front_banding/front_banding910000.png'),
require('./front_banding/front_bandingaa89bd.png'),
require('./front_banding/front_bandingcfcfcf.png'),
require('./front_banding/front_bandingf29c9f.png'),
require('./front_banding/front_bandingf39800.png'),
require('./front_banding/front_bandingfff45c.png'),
require('./front_banding/front_banding626262.png'),
]

const logo = [
    require('../logo.jpg'),
    require('../Unknown.png'),
]
export {

back_sleeve,
back_banding,
back_body,
back_stripe,
front_sleeve,
front_body,
front_button,
front_stripe,
front_banding,
logo,

};
