/* GroupPage action types */
export const CREATE_GROUP = 'CREATE_GROUP'
export const SEARCH_GROUP = 'SEARCH_GROUP'
export const JOIN_GROUP = 'JOIN_GROUP'
export const TO_GROUP_DETAIL = 'TO_GROUP_DETAIL'
export const TO_ADMIN_GROUP = 'TO_ADMIN_GROUP'

export const LIKE_DESIGN = 'LIKE_DESIGN'

export const CHANGE_GROUP_INFO = 'CHANGE_GROUP_INFO'
export const DELETE_GROUP_USER = 'DELETE_GROUP_USER'
export const DELETE_GRUOP_DESIGN = 'DELETE_GROUP_DESIGN'

export const CHANGE_BODY = 'CHANGE_BODY'
export const CHANGE_SLEEVE = 'CHANGE_SLEEVE'
export const CHANGE_BANDING = 'CHANGE_BANDING'
export const CHANGE_STRIPE = 'CHANGE_STRIPE'
export const CHANGE_BUTTON = 'CHANGE_BUTTON'